[tool.poetry]
name = "neuroboard"
version = "0.1.0"
description = ""
authors = ["maxus <maxus.info.mail@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "<3.12,>=3.7"
pyside6 = "^6.4.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
